---
objects:
 duplostein_labor:
  -9:0
  -10:90
 duplostein_alex:
  -11:90
  -12:0
 #template
 #objectname:
  #picturenumber:turningdegree
  #picturenumber:turningdegree
  #several pictures for one object in several angles are usual
