---
objects:
 big_duplo:
  -11:90
  -12:0
  -13:45
  -14:135
 small_duplo:
  -15:0
  -16:45
 duplostein_labor_alt:
  -9:0
  -10:90
 duplostein_alex:
  -11:90
  -12:0
 #template
 #objectname:
  #picturenumber:turningdegree
  #picturenumber:turningdegree
  #several pictures for one object in several angles are usual
